# Generated by Django 3.1.1 on 2020-09-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='wallpaper_23.jpg', upload_to='profile_pics'),
        ),
    ]
