# Generated by Django 3.1.1 on 2020-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20200913_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_image',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
    ]
