# Generated by Django 3.1.1 on 2020-09-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('Food', 'Food'), ('Wear', 'Wear'), ('Shoes', 'Shoes'), ('Electronic', 'Electronic'), ('Mobile', 'Mobile'), ('Book', 'Book'), ('Utilities', 'Utilities'), ('Other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
